### ISSUE TITLE
TLS v1_2 is not supported on latest python 2.7.15

### ISSUE THREAD

**Issue by Azamatshekin** [Zimbra-Community/python-zimbra#26]
I found bug in pythonzimbra/tools/urllib2_tls written as hard code:

`self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file,
                                    ssl_version=ssl.PROTOCOL_TLSv1)` 

I've changed to  `ssl.PROTOCOL_TLSv1` to  `ssl.PROTOCOL_TLSv1_2`, worked successfully for me.

`self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file,
                                    ssl_version=ssl.PROTOCOL_TLSv1_2)` 

alternatively solution:
   remove code in /pythonzimbra/communication.py:

`       if sys.version < '3' and self.url.startswith("https"):`

          `  # Force tlsv1 on https-requests in Python 2`

          `  import tools.urllib2_tls `

please fix it...

**Comment by barrydegraaff** [comment]
done
