### ISSUE TITLE
permission denied: need adequate admin token

### ISSUE THREAD

**Issue by mds1455975151** [Zimbra-Community/python-zimbra#27]
Generate token according to https://wiki.zimbra.com/wiki/Preauth article
version：zcs-8.8.15_GA_3869.RHEL7_64.20190918004220

# user_list.py 
from pythonzimbra.communication import Communication
from pythonzimbra.tools import auth

url = 'https://mail.xxx.com:7071/service/admin/soap'
comm = Communication(url)

user_token = auth.authenticate(
    url,
    'admin@xxx.com',
    'xxx'
)
info_request = comm.gen_request(token=user_token)
info_request.add_request(
    'GetAccountRequest',
    {},
    'urn:zimbraAdmin'
)

info_response = comm.send_request(info_request)
info_response.response_type = 'json'
if not info_response.is_fault():
    print(info_response.get_response()['GetFolderResponse'])
else:
    print(info_response.get_fault_message())

$ python user_list.py 
permission denied: need adequate admin token

**Comment by R13e** [comment]
as described in README.md

> Zimbra currently doesn't support the preauth-method for authentications against the admin-console (URL https://your-zimbra-server:7071/service/admin/soap).

**Comment by barrydegraaff** [comment]
To get an admin auth token in an easy way, log in to the admin console with Google chrome, then hit F12 then go to the Network Tab, reload the screen if needed and in the cookies tab, copy paste the admin auth token.
