### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by aaronlindner** [Zimbra-Community/python-zimbra#5]
Is there any plan to support Python 3?  I'd like to use python-zimbra, but everything we've done here is in Python 3.

**Comment by JocelynDelalande** [comment]
Hi @dploeger sorry for late answer, I took some time to test/review the py3 branch

## Missing things ?

It's missing things from the master, like a setup.py, maybe others things ?

## API change

Seems to be an API change, if I do the AuthRequest by hand, I previously had  a `_content` in the response, I can now grab the token directly from the response.

Before (master):

    {u'authToken': u'0_xxx', u'lifetime': u'43200000', u'skin': u'serenity'}

After (py3 branch):

    {u'authToken': {'_content': u'0_xxx'}, u'lifetime': {'_content': u'43200000'}, 'xmlns': u'urn:zimbraAccount', u'skin': {'_content': u'serenity'}}

Is that intended ? (just asking, IMHO it's ok to break API on major realeses) ? What's the actual change behind ?

### Tests involving special chars ?

I would suggest adding some tests that use special chars. It can be done in dedicated tests but IMHO, the better is to use special chars wherever you can in your test cases. For most people arround the globe, those "special" chars that gives us (developpers) nightmares are their "normal" chars.

e.g: the CreateAccountRequest in `test_admin.py` would be a good candidate, for eg introducing a last_name with some "é" in it

Apart from that points, I did some quick tests using pythonzimbra and it seems to be working well. Thanks for all the job released to community :-)

**Comment by dploeger** [comment]
* Missing things: Yes, I removed the setup.py, because I thought I had wrongly copied it from the pypi-branch. Were you relying on that? I could copy it back
* API change: Yes, I had to do that in 267b50d18eb91b89ec315df25640538426dd0c97. The idea behind it is, that the responses returned by the get_response-method of either RequestXml or RequestJson should be the identical, which they weren't (this was basically a mistake in the RequestXml-class). I will post that warning again in the release notes
* Tests involving special chars: You're right. I will do that.

Could you tell me, if you'd like to have the setup.py back?

**Comment by JocelynDelalande** [comment]
> Missing things: Yes, I removed the setup.py, because I thought I had wrongly copied it from the pypi-branch. Were you relying on that? I could copy it back

Every python dev is relying on that :-)

> API change: Yes, I had to do that in 267b50d. The idea behind it is, that the responses returned by the get_response-method of either RequestXml or RequestJson should be the identical, which they weren't (this was basically a mistake in the RequestXml-class). I will post that warning again in the release notes

Ok, good idea.

> Could you tell me, if you'd like to have the setup.py back?

Sure, I added it myself in #2 a couple of months ago ;-)

**Comment by dploeger** [comment]
Oh, whoops. That was where they came from. :)

Recreated them. Sorry.

I will add the character tests and then merge the branches back together and create an rc.

**Comment by dploeger** [comment]
Added the character tests in 663f799a39365fc613062a2be378187c33a8602b.

Thanks, @JocelynDelalande for your idea about the non-ascii-character tests. That revealed some bugs in request/response handling!

**Comment by dploeger** [comment]
Thanks everyone for contributing your ideas. I will merge the py3 branch now to master and create a release candidate for 2.0
